### ISSUE TITLE
Chapter 2: kubernetes 1.24 serviceaccount creation does not create Secret by default anymore

### ISSUE THREAD

**Issue by jamesclair** [bmuschko/cka-study-guide#3]
See: https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0

**Comment by jimclair** [comment]
I used: `k create token build-bot --duration=9999h`

**Comment by bmuschko** [comment]
Thanks for raising that. Unfortunately, we cannot easily change the content of the book as of now due to the nature of book creation at O'Reilly. It would require a second edition.

The better place to raise those issues is using the [errata](https://www.oreilly.com/catalog/errata.csp?isbn=0636920548300). The GitHub repository just contains the code snippets used in the book. Would you mind raising an issue there?

**Comment by bmuschko** [comment]
Closing the issue, per our discussion above.
