### ISSUE TITLE
Chapter 2: Kubernetes 1.21 deprecated --serviceaccount flag for kubectl run

### ISSUE THREAD

**Issue by jamesclair** [bmuschko/cka-study-guide#4]
Can override the default with `kubectl run build-observer --image=alpine --restart=Never --overrides='{ "spec": { "serviceAccount": "build-bot" }  }'`

**Comment by bmuschko** [comment]
Thanks for raising that. Unfortunately, we cannot easily change the content of the book as of now due to the nature of book creation at O'Reilly. It would require a second edition.

The better place to raise those issues is using the [errata](https://www.oreilly.com/catalog/errata.csp?isbn=0636920548300). The GitHub repository just contains the code snippets used in the book. Would you mind raising an issue there?

**Comment by bmuschko** [comment]
Closing the issue, per our discussion above.
